### ISSUE TITLE
Add project licensing

### ISSUE THREAD

**Issue by Nyumat** [OSU-App-Club/beavsai#5]
Licensing is a pretty important topic, especially given us building this for our university, so [this website](https://choosealicense.com/) is where we should look. 

We want something that's both permissive, but also open to a community and non-binding.

**Comment by Nyumat** [comment]
@nirali112 any status update on this?

**Comment by nirali112** [comment]
not yet, just packed with assignments, will be working on this tomorrow.

**Comment by Nyumat** [comment]
Sounds good, no rush! Good luck on your assignments. 😁

**Comment by nirali112** [comment]
I got to know what to do, it's easy. It's just that, the code somehow stopped running after I pulled the latest code, I'm fixing it.
